# Generated by Django 4.1.3 on 2022-11-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
